using Client.Common;
using Client.CustomValidation;
using Common.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Client.Models.PurchaseRequest
{
    public class LineItemModel
    {
        public long PurchaseRequestLineItemId { get; set; }
        public string PartClientLookupId { get; set; }
        public long PurchaseRequestId { get; set; }
        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationAccountId|" + LocalizeResourceSetConstants.Global)]
        public long ? AccountId { get; set; }
        public long ChargeToID { get; set; }
        public string ChargeToClientLookupId { get; set; }
        public string ChargeTo_Name { get; set; }
        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationChargeType|" + LocalizeResourceSetConstants.Global)]
        public string ChargeType { get; set; }
        public long Creator_PersonnelId { get; set; }
        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationDescription|" + LocalizeResourceSetConstants.Global)]
        public string Description { get; set; }
        public int LineNumber { get; set; }
        public long PartId { get; set; }
        public long PartStoreroomId { get; set; }
        public long PurchaseOrderLineItemId { get; set; }
        //[RegularExpression(@"^\d*\.?\d{0,6}$", ErrorMessage = "globalSixDecimalRegErrMsg|" + LocalizeResourceSetConstants.Global)]
        //[Range(0, 999999999.999999, ErrorMessage = "globalSixDecimalAfterTotalFifteenRegErrMsg|" + LocalizeResourceSetConstants.Global)]
        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationQuantity|" + LocalizeResourceSetConstants.Global)]
        public decimal ? OrderQuantity { get; set; }
        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationUOM|" + LocalizeResourceSetConstants.Global)] 
        public string UnitofMeasure { get; set; }

        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationUnitCost|" + LocalizeResourceSetConstants.Global)]  
        [RegularExpression(@"^\d*\.?\d{0,5}$", ErrorMessage = "globalFiveDecimalRegErrMsg|" + LocalizeResourceSetConstants.Global)]
        [Range(0, 9999999999.99999, ErrorMessage = "GlobalRegErrMsg|" + LocalizeResourceSetConstants.Global)]
        public decimal UnitCost { get; set; }
        public decimal TotalCost { get; set; }
        public string Account_ClientLookupId { get; set; }
        public bool AutoGenerated { get; set; }
        public long ExtractLogId { get; set; }
        public long VendorCatalogItemId { get; set; }
        public int UpdateIndex { get; set; }
        public string ClientLookupId { get; set; }
        public IEnumerable<SelectListItem> AccountList { get; set; }
        public IEnumerable<SelectListItem> ChargeTypeList { get; set; }
        public IEnumerable<SelectListItem> UOMList { get; set; }
        public IEnumerable<SelectListItem> ChargeTypelookUpList { get; set; }

        [Required(ErrorMessage = "ValidationChargeToID|" + LocalizeResourceSetConstants.EventInfo)]
        public string ChargeToClientLookupIdToShow { get; set; }
        public string ViewName { get; set; }
        public bool ispunchout { get; set; }
        [RequiredAsPerUI(UiConfigConstants.PurchaseRequestLineItemAdd, UiConfigConstants.PurchaseRequestLineItemEdit, "PurchaseRequestLineItemId", "0", null, null, ErrorMessage = "validationUOM|" + LocalizeResourceSetConstants.Global)]
        public string PurchaseUOM { get; set; }
        public bool UOMConvRequired { get; set; }
        public decimal UOMConversion { get; set; }
        [FutureDateValidation(ErrorMessage = "Required date should not be a past date")]
        [RequiredIf("IsShopingCart", "true", ErrorMessage = "Please enter required date")]
        public DateTime? RequiredDate { get; set; }
        public bool IsShopingCart { get; set; }//V2-563

        public string status { get; set; }
        #region V2-1046
        public string VendorClientLookupId { get; set; }
        public string VendorName { get; set; }
        public long TotalCount { get; set; }
        #endregion

        #region V2-1063
        public long EstimatedCostsId { get; set; }
        public string WorkOrderClientLookupId { get; set; }
        public decimal UnitCostQuantity { get; set; }
        #endregion
    }
}