/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2011 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */

using System;
using System.Collections;
using System.Data;
using System.Data.SqlClient;
using Database.Business;
using System.Collections.Generic;
using Database.SqlClient;

namespace Database.StoredProcedure
{
    /// <summary>
    /// Access the usp_WorkOrderFlow_Retrieve stored procedure.
    /// </summary>
    public class usp_WorkOrderFlow_Retrieve
    {
        /// <summary>
        /// Constants.
        /// </summary>
        private static string STOREDPROCEDURE_NAME = "usp_WorkOrderFlow_Retrieve";

        /// <summary>
        /// Default constructor.
        /// </summary>
        public usp_WorkOrderFlow_Retrieve()
        {
        }

        /// <summary>
        /// Static method to call the usp_UserData_RetrieveByUserName stored procedure using SqlClient.
        /// </summary>
        /// <param name="command">SqlCommand object to use to call the stored procedure</param>
        /// <param name="processRow">ProcessRow delegate containing method to call to process the row into an object.</param>
        /// <param name="callerUserInfoId">long that identifies the user calling the database</param>
        /// <param name="callerUserName">string that identifies the user calling the database</param>
        /// <param name="clientId">long that contains the value of the @ClientId parameter</param>
        /// <param name="sessionId">System.Guid that contains the value of the @SessionId parameter</param>
        /// <returns>ArrayList containing the results of the query</returns>
        public static List<Object> CallStoredProcedure(
            SqlCommand command,
            long callerUserInfoId,
            string callerUserName,
            b_WorkOrderFlow obj
        )
        {
            List<Object> records = new List<Object>();
            SqlDataReader reader = null;
            SqlParameter RETURN_CODE_parameter = null;
            int retCode = 0;

            // Setup command.
            command.SetProcName(STOREDPROCEDURE_NAME);
            RETURN_CODE_parameter = command.GetReturnCodeParameter();
            command.SetInputParameter(SqlDbType.BigInt, "CallerUserInfoId", callerUserInfoId);
            command.SetStringInputParameter(SqlDbType.NVarChar, "CallerUserName", callerUserName, 256);
            command.SetInputParameter(SqlDbType.BigInt, "ClientId", obj.ClientId);
            command.SetInputParameter(SqlDbType.BigInt, "WorkOrderId", obj.WorkOrder.WorkOrderId);
            command.SetStringInputParameter(SqlDbType.NVarChar, "AssignTo_ClientLookupId", obj.AssignTo_PersonnelClientLookupId, 63);
            command.SetStringInputParameter(SqlDbType.NVarChar, "DelegateTo_ClientLookupId", obj.DelegateTo_PersonnelClientLookupId, 63);

            try
            {
                // Execute stored procedure.
                reader = command.ExecuteReader();

                Object tempRecord = null;

                // Loop through dataset.
                while (reader.Read())
                {
                    // Add the record to the list.
                    tempRecord = b_WorkFlowInstance.ProcessRow(reader);
                }

                records.Add(tempRecord);

                reader.NextResult();

                tempRecord = null;

                // Loop through dataset.
                while (reader.Read())
                {
                    // Add the record to the list.
                    tempRecord = (reader.IsDBNull(0)) ? 0 : reader.GetInt64(0);
                }

                records.Add(tempRecord);

                reader.NextResult();

                tempRecord = null;

                // Loop through dataset.
                while (reader.Read())
                {
                    // Add the record to the list.
                    tempRecord = (reader.IsDBNull(0)) ? 0 :reader.GetInt64(0);
                }

                records.Add(tempRecord);

                reader.NextResult();

                tempRecord = null;

                // Loop through dataset.
                while (reader.Read())
                {
                    // Add the record to the list.
                    tempRecord = (reader.IsDBNull(0)) ? 0 : reader.GetInt64(0);
                }

                records.Add(tempRecord);

            }
            finally
            {
                if (null != reader)
                {
                    if (false == reader.IsClosed)
                    {
                        reader.Close();
                    }
                    reader = null;
                }
            }

            // Process the RETURN_CODE parameter value
            retCode = (int)RETURN_CODE_parameter.Value;
            AbstractTransactionManager.CheckReturnCodeStatus(STOREDPROCEDURE_NAME, retCode);


            // Return the result
            return records;
        }
    }
}