/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2018 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND. MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */

using System;
using System.Data;
using System.Data.SqlClient;
using Database.SqlClient;
using Database.Business;

namespace Database.StoredProcedure
{
    /// <summary>
    /// Access the usp_PartMasterResponse_Create stored procedure.
    /// </summary>
    public class usp_PartMasterResponse_ImportData
    {
        /// <summary>
        /// Constants.
        /// </summary>
        private static string STOREDPROCEDURE_NAME = "usp_PartMasterResponse_ImportData";

        /// <summary>
        /// Default constructor.
        /// </summary>
        public usp_PartMasterResponse_ImportData()
        {
        }

        /// <summary>
        /// Static method to call the usp_PartMasterResponse_Create stored procedure using SqlClient.
        /// </summary>
        /// <param name="command">SqlCommand object to use to call the stored procedure</param>
        /// <param name="callerUserInfoId">long that identifies the user calling the database</param>
        /// <param name="callerUserName">string that identifies the user calling the database</param>
        public static void CallStoredProcedure (
            SqlCommand command,
            long callerUserInfoId,
            string callerUserName,
            b_PartMasterResponse obj
        )
        {
            SqlParameter        RETURN_CODE_parameter = null;
            int                 retCode = 0;

            // Setup command.
            command.SetProcName(STOREDPROCEDURE_NAME);
            RETURN_CODE_parameter = command.GetReturnCodeParameter();
            command.SetInputParameter(SqlDbType.BigInt, "CallerUserInfoId", callerUserInfoId);
            command.SetStringInputParameter(SqlDbType.NVarChar, "CallerUserName", callerUserName, 256);
            command.SetInputParameter(SqlDbType.BigInt, "ClientId", obj.ClientId);
            command.SetInputParameter(SqlDbType.BigInt, "PartMasterResponseId",obj.PartMasterResponseId);
            command.SetInputParameter(SqlDbType.BigInt, "PerformById", obj.PerformById);
            command.SetStringInputParameter(SqlDbType.NVarChar, "TransactionType", obj.TransactionType, 31);
            command.SetOutputParameter(SqlDbType.Bit, "ImportError");

            //command.SetInputParameter(SqlDbType.BigInt, "PartMasterRequestId", obj.PartMasterRequestId);
            //command.SetStringInputParameter(SqlDbType.NVarChar, "RequestType", obj.RequestType, 31);
            //command.SetStringInputParameter(SqlDbType.NVarChar, "EXPartNumber", obj.EXPartNumber,31);
            //command.SetInputParameter(SqlDbType.BigInt, "EXPartId", obj.EXPartId);
            //command.SetStringInputParameter(SqlDbType.NVarChar, "Status", obj.Status, 31);
            //command.SetStringInputParameter(SqlDbType.NVarChar, "ErrorMessage", obj.ErrorMessage, 511);
            //command.SetInputParameter(SqlDbType.BigInt, "ImportLogId", obj.ImportLogId);
            //command.SetOutputParameter(SqlDbType.BigInt, "OutPartHistoryId");
            //command.SetOutputParameter(SqlDbType.BigInt, "OutPartId");
            //command.SetOutputParameter(SqlDbType.BigInt, "OutPartStoreroomId");

            // Execute stored procedure.
            command.ExecuteNonQuery();
            obj.ImportError = command.Parameters["@ImportError"].Value==null?false:(bool)command.Parameters["@ImportError"].Value;

            //obj.OutPartHistoryId = command.Parameters["@OutPartHistoryId"].Value==null?0:(long)command.Parameters["@OutPartHistoryId"].Value;
            //obj.OutPartId = command.Parameters["@OutPartId"].Value==null?0:(long)command.Parameters["@OutPartId"].Value;
            //obj.OutPartStoreroomId = command.Parameters["@OutPartStoreroomId"].Value==null?0:(long)command.Parameters["@OutPartStoreroomId"].Value;

            // Process the RETURN_CODE parameter value
            retCode = (int) RETURN_CODE_parameter.Value;
            AbstractTransactionManager.CheckReturnCodeStatus(STOREDPROCEDURE_NAME, retCode);
        }
    }
}