/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2012 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND. MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */

using System;
using System.Data;
using System.Data.SqlClient;

using Database.Business;
using Database.SqlClient;

namespace Database.StoredProcedure
{
    /// <summary>
    /// Access the usp_AlertUser_Create stored procedure.
    /// </summary>
    public class usp_AlertUser_CreateByPersonnelId
    {
        /// <summary>
        /// Constants.
        /// </summary>
        private static string STOREDPROCEDURE_NAME = "usp_AlertUser_CreateByPersonnelId";

        /// <summary>
        /// Default constructor.
        /// </summary>
        public usp_AlertUser_CreateByPersonnelId()
        {
        }

        /// <summary>
        /// Static method to call the usp_AlertUser_Create stored procedure using SqlClient.
        /// </summary>
        /// <param name="command">SqlCommand object to use to call the stored procedure</param>
        /// <param name="callerUserInfoId">long that identifies the user calling the database</param>
        /// <param name="callerUserName">string that identifies the user calling the database</param>
        public static void CallStoredProcedure (
            SqlCommand command,
            long callerUserInfoId,
            string callerUserName,
            b_AlertUser obj
        )
        {
            SqlParameter        RETURN_CODE_parameter = null;
            int                 retCode = 0;

            // Setup command.
            command.SetProcName(STOREDPROCEDURE_NAME);
            RETURN_CODE_parameter = command.GetReturnCodeParameter();
            command.SetInputParameter(SqlDbType.BigInt, "CallerUserInfoId", callerUserInfoId);
            command.SetStringInputParameter(SqlDbType.NVarChar, "CallerUserName", callerUserName, 256);
            command.SetInputParameter(SqlDbType.BigInt, "ClientId", obj.ClientId);
            command.SetInputParameter(SqlDbType.BigInt, "PersonnelId", obj.PersonnelId);
            command.SetOutputParameter(SqlDbType.BigInt, "AlertUserId");
            command.SetInputParameter(SqlDbType.BigInt, "UserId", obj.UserId);
            command.SetInputParameter(SqlDbType.BigInt, "AlertsId", obj.AlertsId);
            command.SetInputParameter(SqlDbType.DateTime2, "ActiveDate", obj.ActiveDate);
            command.SetStringInputParameter(SqlDbType.NVarChar, "Permission", obj.Permission, 127);
            command.SetInputParameter(SqlDbType.Bit, "IsRead", obj.IsRead);
            command.SetInputParameter(SqlDbType.Bit, "IsDeleted", obj.IsDeleted);

            // Execute stored procedure.
            command.ExecuteNonQuery();

            obj.AlertUserId = (long)command.Parameters["@AlertUserId"].Value;

            // Process the RETURN_CODE parameter value
            retCode = (int) RETURN_CODE_parameter.Value;
            AbstractTransactionManager.CheckReturnCodeStatus(STOREDPROCEDURE_NAME, retCode);
        }


    }
}