/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2011 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */

using System;
using System.Collections;
using System.Text;
using System.Data.SqlClient;
using System.Collections.Generic;
using Database.SqlClient;
using System.Xml.Linq;

namespace Database.Business
{
    /// <summary>
    /// Business object that stores a record from the Timecard table.
    /// </summary>
    public partial class b_ClientEventLog
    {
        #region Property
        public string SiteName { get; set; }
        public string OrderbyColumn { get; set; }
        public string OrderBy { get; set; }
        public int OffSetVal { get; set; }
        public int NextRow { get; set; }
        public string SearchText { get; set; }
        public int TotalCount { get; set; }
        #endregion

        #region Retrieve Client Event Log Records by Client Id
        public static object ProcessRowByClientId(SqlDataReader reader)
        {
            // Create instance of object
            b_ClientEventLog obj = new b_ClientEventLog();

            // Load the object from the database
            obj.LoadFromDatabaseCustom(reader);

            // Return result
            return (object)obj;
        }
        private int LoadFromDatabaseCustom(SqlDataReader reader)
        {
            int i = 0;
            try
            {
                if (false == reader.IsDBNull(i))
                {
                    ClientId = reader.GetInt64(i);
                }
                else
                {
                    ClientId = 0;
                }
                i++;
                if (false == reader.IsDBNull(i))
                {
                    SiteId = reader.GetInt64(i);
                }
                else
                {
                    SiteId = 0;
                }
                i++;
                if (false == reader.IsDBNull(i))
                {
                    ClientEventLogId = reader.GetInt64(i);
                }
                else
                {
                    ClientEventLogId = 0;
                }
                i++;
                if (false == reader.IsDBNull(i))
                {
                    TransactionDate = reader.GetDateTime(i);
                }
                else
                {
                    TransactionDate = DateTime.MinValue;
                }
                i++;
                if (false == reader.IsDBNull(i))
                {
                    Event = reader.GetString(i);
                }
                else
                {
                    Event = "";
                }
                i++;
                if (false == reader.IsDBNull(i))
                {
                    Comments = reader.GetString(i);
                }
                else
                {
                    Comments = "";
                }
                i++;
                if (false == reader.IsDBNull(i))
                {
                    SiteName = reader.GetString(i);
                }
                else
                {
                    SiteName = "";
                }
                i++;
                TotalCount = reader.GetInt32(i++);
            }
            catch (Exception ex)
            {
                // Diagnostics
                StringBuilder missing = new StringBuilder();

                try { reader["ClientId"].ToString(); }
                catch { missing.Append("ClientId"); }

                try { reader["SiteId"].ToString(); }
                catch { missing.Append("SiteId"); }

                try { reader["ClientEventLogId"].ToString(); }
                catch { missing.Append("ClientEventLogId"); }

                try { reader["TransactionDate"].ToString(); }
                catch { missing.Append("TransactionDate"); }

                try { reader["Event"].ToString(); }
                catch { missing.Append("Event"); }

                try { reader["Comments"].ToString(); }
                catch { missing.Append("Comments "); }

                try { reader["SiteName"].ToString(); }
                catch { missing.Append("SiteName "); }

                try { reader["TotalCount"].ToString(); }
                catch { missing.Append("TotalCount "); }

                StringBuilder msg = new StringBuilder();
                msg.Append(string.Format("Exception occurred at index {0}: {1}", i, ex.Message));
                if (missing.Length > 0)
                {
                    msg.Append(string.Format(" The following columns were expected but not found: {0}", missing.ToString()));
                }

                throw new Exception(msg.ToString(), ex);
            }
            return i;
        }
        public void RetrieveByClientIdFromDatabase(
            SqlConnection connection,
            SqlTransaction transaction,
            long callerUserInfoId,
            string callerUserName,
            ref List<b_ClientEventLog> data
        )
        {

            SqlCommand command = null;
            string message = String.Empty;
            List<b_ClientEventLog> results = null;
            data = new List<b_ClientEventLog>();

            try
            {
                // Create the command to use in calling the stored procedures
                command = new SqlCommand();
                command.Connection = connection;
                command.Transaction = transaction;

                // Call the stored procedure to retrieve the data
                results = Database.StoredProcedure.usp_ClientEventLog_RetrieveChunkSearchByClientId_V2.CallStoredProcedure(command, callerUserInfoId, callerUserName, this);

                if (results != null)
                {
                    data = results;
                }
                else
                {
                    data = new List<b_ClientEventLog>();
                }
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }

                message = String.Empty;
                callerUserInfoId = 0;
                callerUserName = String.Empty;
            }
        }
        #endregion
    }

}


