/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2012 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Reflection;

using SOMAX.G4.Data.Database;
using SOMAX.G4.Data.Database.Business;

namespace SOMAX.G4.Data.DataContracts
{
    /// <summary>
    /// Business object that stores a record from the ScheduledJob table.
    /// </summary>
    public partial class ScheduledJob : DataContractBase
    {
        #region Public Methods
        public List<ScheduledJob> UpdateFromDatabaseObjects(List<b_ScheduledJob> dbObjs)
        {
            List<ScheduledJob> configList = new List<ScheduledJob>();

            foreach (b_ScheduledJob dbObj in dbObjs)
            {
                ScheduledJob config = new ScheduledJob();
                config.UpdateFromDatabaseObject(dbObj);

                configList.Add(config);
            }

            return configList;
        }
        #endregion

        #region Transaction Methods
        public List<ScheduledJob> RetrieveAll(DatabaseKey dbKey) 
        {

            ScheduledJob_RetrieveAll trans = new ScheduledJob_RetrieveAll();
            trans.ScheduledJob = this.ToDatabaseObject();
            trans.dbKey = dbKey.ToTransDbKey();
            trans.Execute();
            List<ScheduledJob> configList = UpdateFromDatabaseObjects(trans.ScheduledJobList);

            return configList;
        }

        public List<ScheduledJob> RetrieveActive(DatabaseKey dbKey)
        {

            ScheduledJob_RetrieveActive trans = new ScheduledJob_RetrieveActive();
            trans.dbKey = dbKey.ToTransDbKey();
            trans.Execute();
            List<ScheduledJob> configList = UpdateFromDatabaseObjects(trans.ScheduledJobList);

            return configList;
        }
        #endregion
    }
}
