using System;
using System.ComponentModel.DataAnnotations;

namespace Client.Models.PurchaseOrder
{
    public class POLineItemModel
    {
        public long PurchaseOrderLineItemId { get; set; }
        public long PurchaseOrderId { get; set; }
        public long DepartmentId { get; set; }
        public long StoreroomId { get; set; }
        public long? AccountId { get; set; }
        public long? ChargeToId { get; set; }
        public string ChargeType { get; set; }
        public long CompleteBy_PersonnelId { get; set; }
        public DateTime? CompleteDate { get; set; }
        public long Creator_PersonnelId { get; set; }
        public string Description { get; set; }
        public DateTime? EstimatedDelivery { get; set; }
        public int LineNumber { get; set; }
        public long PartId { get; set; }
        public long PartStoreroomId { get; set; }
        public long PRCreator_PersonnelId { get; set; }
        public long PurchaseRequestId { get; set; }
        public decimal OrderQuantity { get; set; }
        public decimal OrderQuantityOriginal { get; set; }
        public string Status { get; set; }
        public bool Taxable { get; set; }
        public string UnitOfMeasure { get; set; }
        [DisplayFormat(DataFormatString = "{0:C5}")]
        public decimal UnitCost { get; set; }
        public int ExPurchaseOrderLineId { get; set; }
        public string PurchaseUOM { get; set; }
        public decimal UOMConversion { get; set; }
        public decimal PurchaseQuantity { get; set; }
        public decimal PurchaseCost { get; set; }
        public int UpdateIndex { get; set; }
        public string PartClientLookupId { get; set; }
        public decimal TotalCost { get; set; }
        public string ChargeToClientLookupId { get; set; }
        public string ChargeTo_Name { get; set; }
        public string AccountClientLookupId { get; set; }
        public string ErrorMessageRow { get; set; }
        public decimal QuantityReceived { get; set; }
        public decimal QuantityToDate { get; set; }
        public decimal CurrentAverageCost { get; set; }
        public decimal CurrentAppliedCost { get; set; }
        public decimal CurrentOnHandQuantity { get; set; }
        public string StockType { get; set; }
        public decimal QuantityBackOrdered { get; set; }
        public string Status_Display { get; set; }
        public Int64 SiteId { get; set; }
        public string Part_Manufacturer { get; set; }
        public string Part_ManufacturerID { get; set; }
        public string PurchaseOrder_ClientLookupId { get; set; }
        public string PurchaseRequest_ClientLookupId { get; set; }
        public long PurchaseRequest_Creator_PersonnelId { get; set; }
        public bool PurchaseRequest_AutoGenerated { get; set; }
        [DisplayFormat(DataFormatString = "{0:C5}")]
        public decimal LineTotal { get; set; }
        public string PartNumber { get; set; }
        public string SupplierPartId { get; set; }
        public string SupplierPartAuxiliaryId { get; set; }
        public string Classification { get; set; }
        public string RequestorName { get; set; } //V2-1115
        public long EstimatedCostsId { get; set; } //V2-1124

    }
}