using System;

namespace Client.Models.PurchaseOrder
{
    public class PurchaseRequestModel
    {

        public string Creator_PersonnelName { get; set; }
        public string Approved_PersonnelName { get; set; }
        public string Processed_PersonnelName { get; set; }
        public long PurchaseRequestId { get; set; }
        public string ClientLookupId { get; set; }
        public string CreateDates { get; set; }
        public string ApprovedDate { get; set; }
        public string ProcessedDate { get; set; }
        public long PurchaseOrderId { get; set; }
        public bool AutoGenerated { get; set; }

    }
}