/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2012 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */

using System;
using System.Collections;
using System.Data.SqlClient;

namespace Database.Business
{
    /// <summary>
    /// Business object that stores a record from the Contact table.InsertIntoDatabase
    /// </summary>
    public partial class b_Contact : DataBusinessBase
    {

        public void RetrieveByObjectIdFromDatabase(
            SqlConnection connection,
            SqlTransaction transaction,
            long callerUserInfoId,
      string callerUserName,
            ref b_Contact[] data
        )
        {
            Database.SqlClient.ProcessRow<b_Contact> processRow = null;
            ArrayList results = null;
            SqlCommand command = null;
            string message = String.Empty;

            // Initialize the results
            data = new b_Contact[0];

            try
            {
                // Create the command to use in calling the stored procedures
                command = new SqlCommand();
                command.Connection = connection;
                command.Transaction = transaction;

                // Call the stored procedure to retrieve the data
                processRow = new Database.SqlClient.ProcessRow<b_Contact>(reader => { b_Contact obj = new b_Contact(); obj.LoadFromDatabase(reader); return obj; });
                results = Database.StoredProcedure.usp_Contact_RetrieveByObjectId.CallStoredProcedure(command, processRow, callerUserInfoId, callerUserName, ClientId, ObjectId, TableName);

                // Extract the results
                if (null != results)
                {
                    data = (b_Contact[])results.ToArray(typeof(b_Contact));
                }
                else
                {
                    data = new b_Contact[0];
                }

                // Clear the results collection
                if (null != results)
                {
                    results.Clear();
                    results = null;
                }
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }
                processRow = null;
                results = null;
                message = String.Empty;
                callerUserInfoId = 0;
                callerUserName = String.Empty;
            }
        }
    }
}
