/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2011 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */

using System;
using System.Collections;
using System.Text;
using System.Data.SqlClient;
using Database.SqlClient;

namespace Database.Business
{
    /// <summary>
    /// Business object that stores a record from the UserPermission table.
    /// </summary>
    public partial class b_UserPermission 
    {
        /// <summary>
        /// Department property
        /// </summary>
        public string Site { get; set; }

        /// <summary>
        /// Area property
        /// </summary>
        public string Area { get; set; }

        /// <summary>
        /// Department property
        /// </summary>
        public string Department { get; set; }

        /// <summary>
        /// Storeroom property
        /// </summary>
        public string Storeroom { get; set; }

        /// <summary>
        /// Storeroom property
        /// </summary>
        public long SiteCount { get; set; }

        internal static object ProcessRowWithName (SqlDataReader reader)
        {
            // Create instance of object
            b_UserPermission obj = new b_UserPermission();

            // Load the object from the database
            obj.LoadFromDatabaseWithName(reader);

            // Return result
            return (object) obj;
        }

        /// <summary>
        /// Load the current row in the input SqlDataReader into a b_UserPermission object.
        /// This routine should be applied to the usp_UserPermission_RetrieveByPK stored procedure.
        /// This routine should be applied to the usp_UserPermission_RetrieveAll. stored procedure.
        /// </summary>
        /// <param name="reader">SqlDataReader containing the reader to process for the next row</param>
        public void LoadFromDatabaseWithName(SqlDataReader reader)
        {
            int i = 0;
            try
            {

                // ClientId column, bigint, not null
                ClientId = reader.GetInt64(i++);

                // UserPermissionId column, bigint, not null
                UserPermissionId = reader.GetInt64(i++);

                // UserInfoId column, bigint, not null
                UserInfoId = reader.GetInt64(i++);

                // SiteId column, bigint, null
                if (false == reader.IsDBNull(i))
                {
                    SiteId = reader.GetInt64(i);
                }
                i++;

                // AreaId column, bigint, null
                if (false == reader.IsDBNull(i))
                {
                    AreaId = reader.GetInt64(i);
                }
                i++;

                // DepartmentId column, bigint, null
                if (false == reader.IsDBNull(i))
                {
                    DepartmentId = reader.GetInt64(i);
                }
                i++;

                // StoreroomId column, bigint, null
                if (false == reader.IsDBNull(i))
                {
                    StoreroomId = reader.GetInt64(i);
                }
                i++;

                // PermissionType column, nvarchar(1), not null
                PermissionType = reader.GetString(i++);

                // UpdateIndex column, bigint, not null
                UpdateIndex = reader.GetInt64(i++);

                // Site column, nvarchar(15), null
                if (!reader.IsDBNull(i))
                {
                    Site = reader.GetString(i);
                }
                else
                {
                    Site = string.Empty;
                }
                i++;

                // Area column, nvarchar(15), null
                if (!reader.IsDBNull(i))
                {
                    Area = reader.GetString(i);
                }
                else
                {
                    Area = string.Empty;
                }
                i++;

                // Department column, nvarchar(15), null
                if (!reader.IsDBNull(i))
                {
                    Department = reader.GetString(i);
                }
                else
                {
                    Department = string.Empty;
                }
                i++;

                // Storeroom column, nvarchar(15), null
                if (!reader.IsDBNull(i))
                {
                    Storeroom = reader.GetString(i);
                }
                else
                {
                    Storeroom = string.Empty;
                }
                i++;
            }
            catch (Exception ex)
            {
                // Diagnostics
                StringBuilder missing = new StringBuilder();


                try { reader["ClientId"].ToString(); }
                catch { missing.Append("ClientId "); }

                try { reader["UserPermissionId"].ToString(); }
                catch { missing.Append("UserPermissionId "); }

                try { reader["UserInfoId"].ToString(); }
                catch { missing.Append("UserInfoId "); }

                try { reader["SiteId"].ToString(); }
                catch { missing.Append("SiteId "); }

                try { reader["AreaId"].ToString(); }
                catch { missing.Append("AreaId "); }

                try { reader["DepartmentId"].ToString(); }
                catch { missing.Append("DepartmentId "); }

                try { reader["StoreroomId"].ToString(); }
                catch { missing.Append("StoreroomId "); }

                try { reader["PermissionType"].ToString(); }
                catch { missing.Append("PermissionType "); }

                try { reader["UpdateIndex"].ToString(); }
                catch { missing.Append("UpdateIndex "); }


                StringBuilder msg = new StringBuilder();
                msg.Append(string.Format("Exception occurred at index {0}: {1}", i, ex.Message));
                if (missing.Length > 0)
                {
                    msg.Append(string.Format(" The following columns were expected but not found: {0}", missing.ToString()));
                }

                throw new Exception(msg.ToString(), ex);
            }
        }

        public void RetrieveByUserInfoIdFromDatabase(
            SqlConnection connection,
            SqlTransaction transaction,
            long callerUserInfoId,
            string callerUserName,
            ref b_UserPermission[] data
        )
        {
            Database.SqlClient.ProcessRow<b_UserPermission> processRow = null;
            ArrayList results = null;
            SqlCommand command = null;
            string message = String.Empty;

            // Initialize the results
            data = new b_UserPermission[0];

            try
            {
                // Create the command to use in calling the stored procedures
                command = new SqlCommand();
                command.Connection = connection;
                command.Transaction = transaction;

                // Call the stored procedure to retrieve the data
                processRow = new Database.SqlClient.ProcessRow<b_UserPermission>(reader => { b_UserPermission obj = new b_UserPermission(); obj.LoadFromDatabaseWithName(reader); return obj; });
                results = Database.StoredProcedure.usp_UserPermission_RetrieveByUserInfoId.CallStoredProcedure(command, processRow, callerUserInfoId, callerUserName, this);

                // Extract the results
                if (null != results)
                {
                    data = (b_UserPermission[])results.ToArray(typeof(b_UserPermission));
                }
                else
                {
                    data = new b_UserPermission[0];
                }

                // Clear the results collection
                if (null != results)
                {
                    results.Clear();
                    results = null;
                }
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }
                processRow = null;
                results = null;
                message = String.Empty;
                callerUserInfoId = 0;
                callerUserName = String.Empty;
            }
        }

        public void RetrieveWithGroupPermissionByUserInfoIdFromDatabase(
            SqlConnection connection,
            SqlTransaction transaction,
            long callerUserInfoId,
            string callerUserName,
            ref b_UserPermission[] data
        )
        {
            Database.SqlClient.ProcessRow<b_UserPermission> processRow = null;
            ArrayList results = null;
            SqlCommand command = null;
            string message = String.Empty;

            // Initialize the results
            data = new b_UserPermission[0];

            try
            {
                // Create the command to use in calling the stored procedures
                command = new SqlCommand();
                command.Connection = connection;
                command.Transaction = transaction;

                // Call the stored procedure to retrieve the data
                processRow = new Database.SqlClient.ProcessRow<b_UserPermission>(reader => { b_UserPermission obj = new b_UserPermission(); obj.LoadFromDatabaseWithName(reader); return obj; });
                results = Database.StoredProcedure.usp_UserPermission_RetrieveWithGroupPermissionByUserInfoId.CallStoredProcedure(command, processRow, callerUserInfoId, callerUserName, this);

                // Extract the results
                if (null != results)
                {
                    data = (b_UserPermission[])results.ToArray(typeof(b_UserPermission));
                }
                else
                {
                    data = new b_UserPermission[0];
                }

                // Clear the results collection
                if (null != results)
                {
                    results.Clear();
                    results = null;
                }
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }
                processRow = null;
                results = null;
                message = String.Empty;
                callerUserInfoId = 0;
                callerUserName = String.Empty;
            }
        }

        //------------------------------------------Added By Indusnet Technologies----------------------------------
        public void RetrieveByPermissionTypeAndUser(
         SqlConnection connection,
         SqlTransaction transaction,
         long callerUserInfoId,
         string callerUserName,
         ref b_UserPermission[] data
     )
        {
            Database.SqlClient.ProcessRow<b_UserPermission> processRow = null;
            ArrayList results = null;
            SqlCommand command = null;
            string message = String.Empty;

            // Initialize the results
            data = new b_UserPermission[0];

            try
            {
                // Create the command to use in calling the stored procedures
                command = new SqlCommand();
                command.Connection = connection;
                command.Transaction = transaction;

                // Call the stored procedure to retrieve the data
                processRow = new Database.SqlClient.ProcessRow<b_UserPermission>(reader => { b_UserPermission obj = new b_UserPermission(); obj.LoadFromDatabaseWithName(reader); return obj; });
                results = Database.StoredProcedure.usp_UserPermission_RetrieveByPermissionTypeAndUser.CallStoredProcedure(command, processRow, callerUserInfoId, callerUserName, this);

                // Extract the results
                if (null != results)
                {
                    data = (b_UserPermission[])results.ToArray(typeof(b_UserPermission));
                }
                else
                {
                    data = new b_UserPermission[0];
                }

                // Clear the results collection
                if (null != results)
                {
                    results.Clear();
                    results = null;
                }
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }
                processRow = null;
                results = null;
                message = String.Empty;
                callerUserInfoId = 0;
                callerUserName = String.Empty;
            }
        }

        public void DeleteBySiteAndUser(
           SqlConnection connection,
           SqlTransaction transaction,
           long callerUserInfoId,
     string callerUserName
       )
        {
            SqlCommand command = null;

            try
            {
                command = connection.CreateCommand();
                if (null != transaction)
                {
                    command.Transaction = transaction;
                }
                Database.StoredProcedure.usp_UserPermission_DeleteByUserAndSite.CallStoredProcedure(command, callerUserInfoId, callerUserName, this);
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }
            }
        }
//-------------------SOM-828-----------------------------------------------------------------------------------------
        public void RetrieveUserCountsByGrant(SqlConnection connection, SqlTransaction transaction, long callerUserInfoId, string callerUserName)
        {
            SqlCommand command = null;
            string message = String.Empty;
            try
            {
                // Create the command to use in calling the stored procedures
                command = new SqlCommand();
                command.Connection = connection;
                command.Transaction = transaction;

                Database.StoredProcedure.usp_UserPermission_RetrieveByGrant.CallStoredProcedure(command, callerUserInfoId, callerUserName, this);
            }
            finally
            {
                if (null != command)
                {
                    command.Dispose();
                    command = null;
                }
                message = String.Empty;
                callerUserInfoId = 0;
                callerUserName = String.Empty;
            }
        }
    }
}
