/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2011 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

using Database;
using Database.Business;
using Common.Constants;

namespace DataContracts
{
    /// <summary>
    /// Business object that stores a record from the ClientGroupPermission table.
    /// </summary>
    public partial class SecurityGroupPermission : DataContractBase
    {

        #region Private Methods
        public void UpdateFromDatabaseObjectWithNames(b_SecurityGroupPermission dbObj)
        {
            UpdateFromDatabaseObject(dbObj);
            this.Site = dbObj.Site;
            this.Area = dbObj.Area;
            this.Department = dbObj.Department;
            this.Storeroom = dbObj.Storeroom;
        }
        #endregion

        #region Properties

        /// <summary>
        /// Site property
        /// </summary>
        [DataMember]
        public string Site { get; set; }

        /// <summary>
        /// Site property
        /// </summary>
        [DataMember]
        public string Area { get; set; }

        /// <summary>
        /// Department property
        /// </summary>
        [DataMember]
        public string Department { get; set; }

        /// <summary>
        /// Storeroom property
        /// </summary>
        [DataMember]
        public string Storeroom { get; set; }


        public List<SecurityGroupPermission> RetrieveByGroupId(DatabaseKey dbKey)
        {
            SecurityGroupPermission_RetrieveByGroupId trans = new SecurityGroupPermission_RetrieveByGroupId()
            {
                CallerUserInfoId = dbKey.User.UserInfoId,
                CallerUserName = dbKey.UserName
            };
            trans.SecurityGroupPermission = this.ToDatabaseObject();
            trans.dbKey = dbKey.ToTransDbKey();
            trans.Execute();

            List<SecurityGroupPermission> securityPermissionList = new List<SecurityGroupPermission>();

            foreach (b_SecurityGroupPermission securityPermission in trans.SecurityGroupPermissionList)
            {
                SecurityGroupPermission temp = new SecurityGroupPermission();
                temp.UpdateFromDatabaseObjectWithNames(securityPermission);

                securityPermissionList.Add(temp);
            }
            
            return securityPermissionList;
        }
        #endregion
    }
}
