/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2014 by SOMAX Inc.
 * All rights reserved. 
 ***************************************************************************************************
 * Date         JIRA Item Person           Description
 * ===========  ========= ================ ========================================================

 * 2015-Oct-05  SOM-823   Indus Net      Purchase Request Form 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Database;
using Database.Business;
using Common.Enumerations;
using System.Data.SqlClient;
using Database.Client.Custom.Business;

namespace Database
{

    //public class OraclePurchaseRequestExtract_ExtractData_TransactionBaseClass : AbstractTransactionManager
    //{
    //    public OraclePurchaseRequestExtract_ExtractData_TransactionBaseClass()
    //    {
    //        // Set the database in which this table resides.
    //        // This must be called prior to base.PerformLocalValidation(), 
    //        // since that process will validate that the appropriate 
    //        // connection string is set.
    //        UseDatabase = DatabaseTypeEnum.Client;
    //    }

    //    public override void PerformLocalValidation()
    //    {
    //        base.PerformLocalValidation();
         

    //        CallerUserInfoId = dbKey.User.UserInfoId;
    //        CallerUserName = dbKey.UserName;


    //        // Explicitly set tenant id from dbkey
         

    //    }

    

    //    public override void PerformWorkItem()
    //    {
    //        // 
    //    }

    //    public override void Preprocess()
    //    {
    //        // throw new NotImplementedException();
    //    }

    //    public override void Postprocess()
    //    {
    //        // throw new NotImplementedException();
    //    }
    //}


    public class OraclePurchaseRequestExtract_ExtractData : AbstractTransactionManager
    {
        public long ClientId { get; set; }
        public b_OracleReceiptExtract OraclePurchaseRequestExtract { get; set; }
        public List<b_OracleReceiptExtract> OracleReceiptExtractList { get; set; }

        public OraclePurchaseRequestExtract_ExtractData()
        {

            UseDatabase = DatabaseTypeEnum.Client;
           
        }
        public override void PerformLocalValidation()
        {

            base.PerformLocalValidation();

        }
        public override void Preprocess()
        {
            //throw new NotImplementedException();
        }

        public override void Postprocess()
        {
            //throw new NotImplementedException();
        }
       
        public override void PerformWorkItem()
        {
            List<b_OracleReceiptExtract> tmpList= null;

            b_OracleReceiptExtract re = new b_OracleReceiptExtract();            
            re.RetrieveAllOraclePurchaseRequestForExport(this.Connection, this.Transaction, CallerUserInfoId, CallerUserName, ref tmpList, ClientId);
            OracleReceiptExtractList = tmpList;

        }

    }
}
