/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2017 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Database;
using Database.Business;
using Common.Enumerations;
using System.Data.SqlClient;

namespace Database
{

    public class SensorReading_RetrieveBySensorID : SensorReading_TransactionBaseClass
    {
        public List<b_SensorReading> SensorReadingList { get; set; }

        public override void PerformLocalValidation()
        {
            base.PerformLocalValidation();
            if (SensorReading.SensorID == 0)
            {
                string message = "SensorReading has an invalid ID.";
                throw new Exception(message);
            }
        }

        public override void PerformWorkItem()
        {
            base.UseTransaction = false;
            List<b_SensorReading> tmpArray = null;

            SensorReading.RetrieveBySensorIDFromDatabase(this.Connection, this.Transaction, CallerUserInfoId, CallerUserName, ref tmpArray);

            SensorReadingList = new List<b_SensorReading>();

            foreach (b_SensorReading tmpObj in tmpArray)
            {
                SensorReadingList.Add(tmpObj);
            }
        }

    }
    public class SensorReading_RetrieveAllByDate : SensorReading_TransactionBaseClass
    {
        public List<b_SensorReading> SensorReadingList { get; set; }

        public override void Preprocess()
        {
            //throw new NotImplementedException();
        }

        public override void Postprocess()
        {
            //throw new NotImplementedException();
        }

        public override void PerformLocalValidation()
        {
            base.PerformLocalValidation();
        }

        public override void PerformWorkItem()
        {
            base.UseTransaction = false;
            List<b_SensorReading> tmpArray = null;

            SensorReading.RetrieveAllByDate(this.Connection, this.Transaction, CallerUserInfoId, CallerUserName, ref tmpArray);

            SensorReadingList = new List<b_SensorReading>();

            foreach (b_SensorReading tmpObj in tmpArray)
            {
                SensorReadingList.Add(tmpObj);
            }
        }
    }

    public class SensorReading_RetrieveBySensorIDForTimeSeriesChart : SensorReading_TransactionBaseClass
    {
        public List<b_SensorReading> SensorReadingList { get; set; }

        public override void PerformLocalValidation()
        {
            base.PerformLocalValidation();
            if (SensorReading.SensorID == 0)
            {
                string message = "SensorReading has an invalid ID.";
                throw new Exception(message);
            }
        }

        public override void PerformWorkItem()
        {
            base.UseTransaction = false;
            List<b_SensorReading> tmpArray = null;

            SensorReading.RetrieveBySensorIDForTimeSeriesChart(this.Connection, this.Transaction, CallerUserInfoId, CallerUserName, ref tmpArray);

            SensorReadingList = new List<b_SensorReading>();

            foreach (b_SensorReading tmpObj in tmpArray)
            {
                SensorReadingList.Add(tmpObj);
            }
        }

    }

}
