/*
 ******************************************************************************
 * PROPRIETARY DATA 
 ******************************************************************************
 * This work is PROPRIETARY to SOMAX Inc and is protected 
 * under Federal Law as an unpublished Copyrighted work and under State Law as 
 * a Trade Secret. 
 ******************************************************************************
 * Copyright (c) 2020 by SOMAX Inc.
 * All rights reserved. 
 ******************************************************************************
 * THIS CODE HAS BEEN GENERATED BY AN AUTOMATED PROCESS.
 * DO NOT MODIFY BY HAND.    MODIFY THE TEMPLATE AND REGENERATE THE CODE 
 * USING THE CURRENT DATABASE IF MODIFICATIONS ARE NEEDED.
 ******************************************************************************
 */


using Database.Business;

using System;


namespace Database
{
        public class UserEventLog_CreateForAdmin : UserEventLog_TransactionBaseClass
        {
        public long customClientId { get; set; }
        public override void PerformLocalValidation()
            {
                base.PerformLocalValidation();
                if (UserEventLog.UserEventLogId > 0)
                {
                    string message = "UserEventLog has an invalid ID.";
                    throw new Exception(message);
                }
            }
            public override void PerformWorkItem()
            {
               UserEventLog.ClientId = this.customClientId;
                UserEventLog.InsertIntoDatabase(this.Connection, this.Transaction, CallerUserInfoId, CallerUserName);
            }

            public override void Postprocess()
            {
                base.Postprocess();
                System.Diagnostics.Debug.Assert(UserEventLog.UserEventLogId > 0);
            }
        }


    
}
